/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as HubRouteImport } from './routes/hub'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAgentsRouteImport } from './routes/admin.agents'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminExceptionsRouteImport } from './routes/admin.exceptions'
import { Route as AdminFleetRouteImport } from './routes/admin.fleet'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as CustomerAddressesRouteImport } from './routes/customer.addresses'
import { Route as CustomerBookRouteImport } from './routes/customer.book'
import { Route as CustomerInvoicesRouteImport } from './routes/customer.invoices'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerPaymentsRouteImport } from './routes/customer.payments'
import { Route as CustomerReturnsRouteImport } from './routes/customer.returns'
import { Route as CustomerShipmentsRouteImport } from './routes/customer.shipments'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DriverDeliveriesRouteImport } from './routes/driver.deliveries'
import { Route as DriverEarningsRouteImport } from './routes/driver.earnings'
import { Route as DriverExceptionsRouteImport } from './routes/driver.exceptions'
import { Route as DriverMyRouteRouteImport } from './routes/driver.my-route'
import { Route as DriverPerformanceRouteImport } from './routes/driver.performance'
import { Route as HubIndexRouteImport } from './routes/hub.index'
import { Route as HubAnalyticsRouteImport } from './routes/hub.analytics'
import { Route as HubDispatchRouteImport } from './routes/hub.dispatch'
import { Route as HubExceptionsRouteImport } from './routes/hub.exceptions'
import { Route as HubIntakeRouteImport } from './routes/hub.intake'
import { Route as HubLoadRouteImport } from './routes/hub.load'
import { Route as HubMedicalRouteImport } from './routes/hub.medical'
import { Route as HubTransfersRouteImport } from './routes/hub.transfers'
import { Route as AdminHubsIndexRouteImport } from './routes/admin.hubs.index'
import { Route as AdminHubsIdRouteImport } from './routes/admin.hubs.$id'
import { Route as AdminShipmentsIndexRouteImport } from './routes/admin.shipments.index'
import { Route as AdminShipmentsTrackingIdRouteImport } from './routes/admin.shipments.$trackingId'
import { Route as CustomerTrackIndexRouteImport } from './routes/customer.track.index'
import { Route as CustomerTrackIdRouteImport } from './routes/customer.track.$id'
import { Route as DriverShipmentIdRouteImport } from './routes/driver.shipment.$id'
import { Route as HubShipmentsTrackingIdRouteImport } from './routes/hub.shipments.$trackingId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const HubRoute = HubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgentsRoute = AdminAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExceptionsRoute = AdminExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFleetRoute = AdminFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAddressesRoute = CustomerAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookRoute = CustomerBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerInvoicesRoute = CustomerInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerPaymentsRoute = CustomerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerReturnsRoute = CustomerReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerShipmentsRoute = CustomerShipmentsRouteImport.update({
  id: '/shipments',
  path: '/shipments',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CustomerRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const DriverDeliveriesRoute = DriverDeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => DriverRoute,
} as any)
const DriverEarningsRoute = DriverEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => DriverRoute,
} as any)
const DriverExceptionsRoute = DriverExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => DriverRoute,
} as any)
const DriverMyRouteRoute = DriverMyRouteRouteImport.update({
  id: '/my-route',
  path: '/my-route',
  getParentRoute: () => DriverRoute,
} as any)
const DriverPerformanceRoute = DriverPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => DriverRoute,
} as any)
const HubIndexRoute = HubIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HubRoute,
} as any)
const HubAnalyticsRoute = HubAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => HubRoute,
} as any)
const HubDispatchRoute = HubDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => HubRoute,
} as any)
const HubExceptionsRoute = HubExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => HubRoute,
} as any)
const HubIntakeRoute = HubIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => HubRoute,
} as any)
const HubLoadRoute = HubLoadRouteImport.update({
  id: '/load',
  path: '/load',
  getParentRoute: () => HubRoute,
} as any)
const HubMedicalRoute = HubMedicalRouteImport.update({
  id: '/medical',
  path: '/medical',
  getParentRoute: () => HubRoute,
} as any)
const HubTransfersRoute = HubTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => HubRoute,
} as any)
const AdminHubsIndexRoute = AdminHubsIndexRouteImport.update({
  id: '/hubs/',
  path: '/hubs/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHubsIdRoute = AdminHubsIdRouteImport.update({
  id: '/hubs/$id',
  path: '/hubs/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsIndexRoute = AdminShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShipmentsTrackingIdRoute =
  AdminShipmentsTrackingIdRouteImport.update({
    id: '/shipments/$trackingId',
    path: '/shipments/$trackingId',
    getParentRoute: () => AdminRoute,
  } as any)
const CustomerTrackIndexRoute = CustomerTrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerTrackIdRoute = CustomerTrackIdRouteImport.update({
  id: '/track/$id',
  path: '/track/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const DriverShipmentIdRoute = DriverShipmentIdRouteImport.update({
  id: '/shipment/$id',
  path: '/shipment/$id',
  getParentRoute: () => DriverRoute,
} as any)
const HubShipmentsTrackingIdRoute = HubShipmentsTrackingIdRouteImport.update({
  id: '/shipments/$trackingId',
  path: '/shipments/$trackingId',
  getParentRoute: () => HubRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/hub': typeof HubRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/returns': typeof CustomerReturnsRoute
  '/customer/shipments': typeof CustomerShipmentsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/exceptions': typeof DriverExceptionsRoute
  '/driver/my-route': typeof DriverMyRouteRoute
  '/driver/performance': typeof DriverPerformanceRoute
  '/hub/analytics': typeof HubAnalyticsRoute
  '/hub/dispatch': typeof HubDispatchRoute
  '/hub/exceptions': typeof HubExceptionsRoute
  '/hub/intake': typeof HubIntakeRoute
  '/hub/load': typeof HubLoadRoute
  '/hub/medical': typeof HubMedicalRoute
  '/hub/transfers': typeof HubTransfersRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/hub/': typeof HubIndexRoute
  '/admin/hubs/$id': typeof AdminHubsIdRoute
  '/admin/shipments/$trackingId': typeof AdminShipmentsTrackingIdRoute
  '/customer/track/$id': typeof CustomerTrackIdRoute
  '/driver/shipment/$id': typeof DriverShipmentIdRoute
  '/hub/shipments/$trackingId': typeof HubShipmentsTrackingIdRoute
  '/admin/hubs/': typeof AdminHubsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
  '/customer/track/': typeof CustomerTrackIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/returns': typeof CustomerReturnsRoute
  '/customer/shipments': typeof CustomerShipmentsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/exceptions': typeof DriverExceptionsRoute
  '/driver/my-route': typeof DriverMyRouteRoute
  '/driver/performance': typeof DriverPerformanceRoute
  '/hub/analytics': typeof HubAnalyticsRoute
  '/hub/dispatch': typeof HubDispatchRoute
  '/hub/exceptions': typeof HubExceptionsRoute
  '/hub/intake': typeof HubIntakeRoute
  '/hub/load': typeof HubLoadRoute
  '/hub/medical': typeof HubMedicalRoute
  '/hub/transfers': typeof HubTransfersRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/driver': typeof DriverIndexRoute
  '/hub': typeof HubIndexRoute
  '/admin/hubs/$id': typeof AdminHubsIdRoute
  '/admin/shipments/$trackingId': typeof AdminShipmentsTrackingIdRoute
  '/customer/track/$id': typeof CustomerTrackIdRoute
  '/driver/shipment/$id': typeof DriverShipmentIdRoute
  '/hub/shipments/$trackingId': typeof HubShipmentsTrackingIdRoute
  '/admin/hubs': typeof AdminHubsIndexRoute
  '/admin/shipments': typeof AdminShipmentsIndexRoute
  '/customer/track': typeof CustomerTrackIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer': typeof CustomerRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/hub': typeof HubRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/agents': typeof AdminAgentsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/exceptions': typeof AdminExceptionsRoute
  '/admin/fleet': typeof AdminFleetRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/book': typeof CustomerBookRoute
  '/customer/invoices': typeof CustomerInvoicesRoute
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/payments': typeof CustomerPaymentsRoute
  '/customer/returns': typeof CustomerReturnsRoute
  '/customer/shipments': typeof CustomerShipmentsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/driver/deliveries': typeof DriverDeliveriesRoute
  '/driver/earnings': typeof DriverEarningsRoute
  '/driver/exceptions': typeof DriverExceptionsRoute
  '/driver/my-route': typeof DriverMyRouteRoute
  '/driver/performance': typeof DriverPerformanceRoute
  '/hub/analytics': typeof HubAnalyticsRoute
  '/hub/dispatch': typeof HubDispatchRoute
  '/hub/exceptions': typeof HubExceptionsRoute
  '/hub/intake': typeof HubIntakeRoute
  '/hub/load': typeof HubLoadRoute
  '/hub/medical': typeof HubMedicalRoute
  '/hub/transfers': typeof HubTransfersRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/hub/': typeof HubIndexRoute
  '/admin/hubs/$id': typeof AdminHubsIdRoute
  '/admin/shipments/$trackingId': typeof AdminShipmentsTrackingIdRoute
  '/customer/track/$id': typeof CustomerTrackIdRoute
  '/driver/shipment/$id': typeof DriverShipmentIdRoute
  '/hub/shipments/$trackingId': typeof HubShipmentsTrackingIdRoute
  '/admin/hubs/': typeof AdminHubsIndexRoute
  '/admin/shipments/': typeof AdminShipmentsIndexRoute
  '/customer/track/': typeof CustomerTrackIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer'
    | '/driver'
    | '/hub'
    | '/login'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/exceptions'
    | '/admin/fleet'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/book'
    | '/customer/invoices'
    | '/customer/notifications'
    | '/customer/payments'
    | '/customer/returns'
    | '/customer/shipments'
    | '/customer/support'
    | '/driver/deliveries'
    | '/driver/earnings'
    | '/driver/exceptions'
    | '/driver/my-route'
    | '/driver/performance'
    | '/hub/analytics'
    | '/hub/dispatch'
    | '/hub/exceptions'
    | '/hub/intake'
    | '/hub/load'
    | '/hub/medical'
    | '/hub/transfers'
    | '/admin/'
    | '/customer/'
    | '/driver/'
    | '/hub/'
    | '/admin/hubs/$id'
    | '/admin/shipments/$trackingId'
    | '/customer/track/$id'
    | '/driver/shipment/$id'
    | '/hub/shipments/$trackingId'
    | '/admin/hubs/'
    | '/admin/shipments/'
    | '/customer/track/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/exceptions'
    | '/admin/fleet'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/book'
    | '/customer/invoices'
    | '/customer/notifications'
    | '/customer/payments'
    | '/customer/returns'
    | '/customer/shipments'
    | '/customer/support'
    | '/driver/deliveries'
    | '/driver/earnings'
    | '/driver/exceptions'
    | '/driver/my-route'
    | '/driver/performance'
    | '/hub/analytics'
    | '/hub/dispatch'
    | '/hub/exceptions'
    | '/hub/intake'
    | '/hub/load'
    | '/hub/medical'
    | '/hub/transfers'
    | '/admin'
    | '/customer'
    | '/driver'
    | '/hub'
    | '/admin/hubs/$id'
    | '/admin/shipments/$trackingId'
    | '/customer/track/$id'
    | '/driver/shipment/$id'
    | '/hub/shipments/$trackingId'
    | '/admin/hubs'
    | '/admin/shipments'
    | '/customer/track'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer'
    | '/driver'
    | '/hub'
    | '/login'
    | '/admin/agents'
    | '/admin/analytics'
    | '/admin/exceptions'
    | '/admin/fleet'
    | '/admin/notifications'
    | '/admin/payments'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/users'
    | '/customer/addresses'
    | '/customer/book'
    | '/customer/invoices'
    | '/customer/notifications'
    | '/customer/payments'
    | '/customer/returns'
    | '/customer/shipments'
    | '/customer/support'
    | '/driver/deliveries'
    | '/driver/earnings'
    | '/driver/exceptions'
    | '/driver/my-route'
    | '/driver/performance'
    | '/hub/analytics'
    | '/hub/dispatch'
    | '/hub/exceptions'
    | '/hub/intake'
    | '/hub/load'
    | '/hub/medical'
    | '/hub/transfers'
    | '/admin/'
    | '/customer/'
    | '/driver/'
    | '/hub/'
    | '/admin/hubs/$id'
    | '/admin/shipments/$trackingId'
    | '/customer/track/$id'
    | '/driver/shipment/$id'
    | '/hub/shipments/$trackingId'
    | '/admin/hubs/'
    | '/admin/shipments/'
    | '/customer/track/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerRoute: typeof CustomerRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  HubRoute: typeof HubRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hub': {
      id: '/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof HubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agents': {
      id: '/admin/agents'
      path: '/agents'
      fullPath: '/admin/agents'
      preLoaderRoute: typeof AdminAgentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/exceptions': {
      id: '/admin/exceptions'
      path: '/exceptions'
      fullPath: '/admin/exceptions'
      preLoaderRoute: typeof AdminExceptionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fleet': {
      id: '/admin/fleet'
      path: '/fleet'
      fullPath: '/admin/fleet'
      preLoaderRoute: typeof AdminFleetRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/addresses': {
      id: '/customer/addresses'
      path: '/addresses'
      fullPath: '/customer/addresses'
      preLoaderRoute: typeof CustomerAddressesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/book': {
      id: '/customer/book'
      path: '/book'
      fullPath: '/customer/book'
      preLoaderRoute: typeof CustomerBookRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/invoices': {
      id: '/customer/invoices'
      path: '/invoices'
      fullPath: '/customer/invoices'
      preLoaderRoute: typeof CustomerInvoicesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/payments': {
      id: '/customer/payments'
      path: '/payments'
      fullPath: '/customer/payments'
      preLoaderRoute: typeof CustomerPaymentsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/returns': {
      id: '/customer/returns'
      path: '/returns'
      fullPath: '/customer/returns'
      preLoaderRoute: typeof CustomerReturnsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/shipments': {
      id: '/customer/shipments'
      path: '/shipments'
      fullPath: '/customer/shipments'
      preLoaderRoute: typeof CustomerShipmentsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/deliveries': {
      id: '/driver/deliveries'
      path: '/deliveries'
      fullPath: '/driver/deliveries'
      preLoaderRoute: typeof DriverDeliveriesRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/earnings': {
      id: '/driver/earnings'
      path: '/earnings'
      fullPath: '/driver/earnings'
      preLoaderRoute: typeof DriverEarningsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/exceptions': {
      id: '/driver/exceptions'
      path: '/exceptions'
      fullPath: '/driver/exceptions'
      preLoaderRoute: typeof DriverExceptionsRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/my-route': {
      id: '/driver/my-route'
      path: '/my-route'
      fullPath: '/driver/my-route'
      preLoaderRoute: typeof DriverMyRouteRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/performance': {
      id: '/driver/performance'
      path: '/performance'
      fullPath: '/driver/performance'
      preLoaderRoute: typeof DriverPerformanceRouteImport
      parentRoute: typeof DriverRoute
    }
    '/hub/': {
      id: '/hub/'
      path: '/'
      fullPath: '/hub/'
      preLoaderRoute: typeof HubIndexRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/analytics': {
      id: '/hub/analytics'
      path: '/analytics'
      fullPath: '/hub/analytics'
      preLoaderRoute: typeof HubAnalyticsRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/dispatch': {
      id: '/hub/dispatch'
      path: '/dispatch'
      fullPath: '/hub/dispatch'
      preLoaderRoute: typeof HubDispatchRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/exceptions': {
      id: '/hub/exceptions'
      path: '/exceptions'
      fullPath: '/hub/exceptions'
      preLoaderRoute: typeof HubExceptionsRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/intake': {
      id: '/hub/intake'
      path: '/intake'
      fullPath: '/hub/intake'
      preLoaderRoute: typeof HubIntakeRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/load': {
      id: '/hub/load'
      path: '/load'
      fullPath: '/hub/load'
      preLoaderRoute: typeof HubLoadRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/medical': {
      id: '/hub/medical'
      path: '/medical'
      fullPath: '/hub/medical'
      preLoaderRoute: typeof HubMedicalRouteImport
      parentRoute: typeof HubRoute
    }
    '/hub/transfers': {
      id: '/hub/transfers'
      path: '/transfers'
      fullPath: '/hub/transfers'
      preLoaderRoute: typeof HubTransfersRouteImport
      parentRoute: typeof HubRoute
    }
    '/admin/hubs/': {
      id: '/admin/hubs/'
      path: '/hubs'
      fullPath: '/admin/hubs/'
      preLoaderRoute: typeof AdminHubsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hubs/$id': {
      id: '/admin/hubs/$id'
      path: '/hubs/$id'
      fullPath: '/admin/hubs/$id'
      preLoaderRoute: typeof AdminHubsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments/': {
      id: '/admin/shipments/'
      path: '/shipments'
      fullPath: '/admin/shipments/'
      preLoaderRoute: typeof AdminShipmentsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/shipments/$trackingId': {
      id: '/admin/shipments/$trackingId'
      path: '/shipments/$trackingId'
      fullPath: '/admin/shipments/$trackingId'
      preLoaderRoute: typeof AdminShipmentsTrackingIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/track/': {
      id: '/customer/track/'
      path: '/track'
      fullPath: '/customer/track/'
      preLoaderRoute: typeof CustomerTrackIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/track/$id': {
      id: '/customer/track/$id'
      path: '/track/$id'
      fullPath: '/customer/track/$id'
      preLoaderRoute: typeof CustomerTrackIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/driver/shipment/$id': {
      id: '/driver/shipment/$id'
      path: '/shipment/$id'
      fullPath: '/driver/shipment/$id'
      preLoaderRoute: typeof DriverShipmentIdRouteImport
      parentRoute: typeof DriverRoute
    }
    '/hub/shipments/$trackingId': {
      id: '/hub/shipments/$trackingId'
      path: '/shipments/$trackingId'
      fullPath: '/hub/shipments/$trackingId'
      preLoaderRoute: typeof HubShipmentsTrackingIdRouteImport
      parentRoute: typeof HubRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAgentsRoute: typeof AdminAgentsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminExceptionsRoute: typeof AdminExceptionsRoute
  AdminFleetRoute: typeof AdminFleetRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminHubsIdRoute: typeof AdminHubsIdRoute
  AdminShipmentsTrackingIdRoute: typeof AdminShipmentsTrackingIdRoute
  AdminHubsIndexRoute: typeof AdminHubsIndexRoute
  AdminShipmentsIndexRoute: typeof AdminShipmentsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgentsRoute: AdminAgentsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminExceptionsRoute: AdminExceptionsRoute,
  AdminFleetRoute: AdminFleetRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminHubsIdRoute: AdminHubsIdRoute,
  AdminShipmentsTrackingIdRoute: AdminShipmentsTrackingIdRoute,
  AdminHubsIndexRoute: AdminHubsIndexRoute,
  AdminShipmentsIndexRoute: AdminShipmentsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CustomerRouteChildren {
  CustomerAddressesRoute: typeof CustomerAddressesRoute
  CustomerBookRoute: typeof CustomerBookRoute
  CustomerInvoicesRoute: typeof CustomerInvoicesRoute
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerPaymentsRoute: typeof CustomerPaymentsRoute
  CustomerReturnsRoute: typeof CustomerReturnsRoute
  CustomerShipmentsRoute: typeof CustomerShipmentsRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerTrackIdRoute: typeof CustomerTrackIdRoute
  CustomerTrackIndexRoute: typeof CustomerTrackIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAddressesRoute: CustomerAddressesRoute,
  CustomerBookRoute: CustomerBookRoute,
  CustomerInvoicesRoute: CustomerInvoicesRoute,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerPaymentsRoute: CustomerPaymentsRoute,
  CustomerReturnsRoute: CustomerReturnsRoute,
  CustomerShipmentsRoute: CustomerShipmentsRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerTrackIdRoute: CustomerTrackIdRoute,
  CustomerTrackIndexRoute: CustomerTrackIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface DriverRouteChildren {
  DriverDeliveriesRoute: typeof DriverDeliveriesRoute
  DriverEarningsRoute: typeof DriverEarningsRoute
  DriverExceptionsRoute: typeof DriverExceptionsRoute
  DriverMyRouteRoute: typeof DriverMyRouteRoute
  DriverPerformanceRoute: typeof DriverPerformanceRoute
  DriverIndexRoute: typeof DriverIndexRoute
  DriverShipmentIdRoute: typeof DriverShipmentIdRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverDeliveriesRoute: DriverDeliveriesRoute,
  DriverEarningsRoute: DriverEarningsRoute,
  DriverExceptionsRoute: DriverExceptionsRoute,
  DriverMyRouteRoute: DriverMyRouteRoute,
  DriverPerformanceRoute: DriverPerformanceRoute,
  DriverIndexRoute: DriverIndexRoute,
  DriverShipmentIdRoute: DriverShipmentIdRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

interface HubRouteChildren {
  HubAnalyticsRoute: typeof HubAnalyticsRoute
  HubDispatchRoute: typeof HubDispatchRoute
  HubExceptionsRoute: typeof HubExceptionsRoute
  HubIntakeRoute: typeof HubIntakeRoute
  HubLoadRoute: typeof HubLoadRoute
  HubMedicalRoute: typeof HubMedicalRoute
  HubTransfersRoute: typeof HubTransfersRoute
  HubIndexRoute: typeof HubIndexRoute
  HubShipmentsTrackingIdRoute: typeof HubShipmentsTrackingIdRoute
}

const HubRouteChildren: HubRouteChildren = {
  HubAnalyticsRoute: HubAnalyticsRoute,
  HubDispatchRoute: HubDispatchRoute,
  HubExceptionsRoute: HubExceptionsRoute,
  HubIntakeRoute: HubIntakeRoute,
  HubLoadRoute: HubLoadRoute,
  HubMedicalRoute: HubMedicalRoute,
  HubTransfersRoute: HubTransfersRoute,
  HubIndexRoute: HubIndexRoute,
  HubShipmentsTrackingIdRoute: HubShipmentsTrackingIdRoute,
}

const HubRouteWithChildren = HubRoute._addFileChildren(HubRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerRoute: CustomerRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  HubRoute: HubRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
